### ISSUE TITLE
Updating n8n Digitalocean app

### ISSUE THREAD

**Issue by Stockotaco** [johnkraczek/n8n-app-do#1]
Hi John, 

Thank you for providing the ability to 1 click install on Digitalocean! Super helpful to get things going. 

How do you update to the latest version of n8n though?

**Comment by emeagenciadigital** [comment]
Hi 👋,

I’m a YouTube follower , thank you for this Esaú setup. 

Already install but the version is already 4 month old. Please add to the readme  instructions for updating.

**Comment by johnkraczek** [comment]
you should be able to simply force a redeploy on the app in the digitalocean dashboard. it will pull the latest version. 
you may need to check the clear build-cache when you do the force redeploy
